# 通道分析配置参数
# 上升通道回归模块配置

ascending_channel:
  # 通道宽度倍数 (±k·σ)
  k: 2.0
  
  # 窗口最长天数（超出后向右滑动）
  L_max: 120
  
  # 滑动时一次剔除最早 delta_cut 天
  delta_cut: 5
  
  # 判断 pivot low 宽度 (m 左 m 右更高)
  pivot_m: 3
  
  # 最小数据要求
  min_data_points: 60
  
  # 最小回归拟合优度R²阈值，低于此视为无效通道
  R2_min: 0.20
  # 通道宽度下限 (上沿-下沿)/mid_today，小于此视为过窄
  width_pct_min: 0.04
  # 通道宽度上限，超过此视为过宽
  width_pct_max: 0.12
  
  # 日志级别
  log_level: "INFO"
  
  # 性能优化
  performance:
    # 是否启用缓存
    enable_cache: true
    # 缓存过期时间（秒）
    cache_ttl: 3600
    # 并行计算线程数
    max_workers: 4

# 通道状态定义
channel_status:
  NORMAL: "通道正常"
  BREAKOUT: "突破上沿"
  BREAKDOWN: "跌破下沿/失效"
  ASCENDING_WEAK: "弱上升通道"

# 异常处理配置
error_handling:
  # 是否抛出异常
  raise_exceptions: true
  # 默认返回值
  default_return: null
  # 重试次数
  max_retries: 3 